common:
  labels: &common-labels
  - { name: "blocked", color: "#b60205" }
  - { name: "status:research", color: "#1d76db" }
  - { name: "type:bug", color: "#f7c6c7" }
  - { name: "type:critical", color: "#e11d21" }
  - { name: "type:docs", color: "#bfdadc" }
  - { name: "type:feature", color: "#006b75" }
  - { name: "type:refactoring", color: "#bfe5bf" }
  - { name: "type:task", color: "#009800" }

projects:
  your/project:
    labels: *common-labels
